### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by apizzuto** [icecube/FIRESONG#16]
"I [Ignacio] will take care of this over the next few months actually, and we can steal material from Chris’ PhD thesis"

**Comment by itaboada** [comment]
To do: 
* Update documentation for FIRESONG.py.
* Write documentation for Legend.py

**Comment by itaboada** [comment]
Alex has added API documentation. Also needed is an expanded and reviewed README.md
In the README.md we need: description of dependencies (cosmolopy, numpy, scipy, python3); installation instructions; description of command line options; description of units; description of output; example usage of Firesong.py, Legend.py and FluxPDF.py.

**Comment by itaboada** [comment]
All done!
