### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by apizzuto** [icecube/FIRESONG#26]
There are various test scripts, but most of them don't do anything. It would be good to actually add tests for test_Firesong at the very least, potentially checking things in the header as well as average fluxes / redshifts.
Similar tests should be implemented for the other modules

**Comment by apizzuto** [comment]
Addressed in https://github.com/icecube/FIRESONG/pull/42, pretty much everything is covered by tests now except for Power law luminosity functions and the Legend simulation stuff

**Comment by itaboada** [comment]
All unit tests have been now implemented.
