### ISSUE TITLE
Simulate transient sources, NOT TESTED YET!

### ISSUE THREAD

**Issue by renereimann** [icecube/FIRESONG#32]
In https://github.com/icecube/FIRESONG/blob/base/Firesong.py#L147 the helper string says "NOT TESTED YET!". 
We should make sure that the functionality is tested and remove the warning.

Same in https://github.com/icecube/FIRESONG/blob/base/FluxPDF.py#L138

**Comment by itaboada** [comment]
Fixed this for Firesong. Theo should confirm it's ok to remove for FluxPDF.py
