### ISSUE TITLE
Put the G back in FIRESONG: Add utility/module to calculate g-ray fluxes given nu fluxes

### ISSUE THREAD

**Issue by itaboada** [icecube/FIRESONG#39]
This should be done for pp and p-gamma interactions. 
It could be a module that is called as an option itself in FIRESONG, which would output gamma-ray flux or as a standalone program that converts numu fluxes to gamma ray fluxes. Should be easy to code.

**Comment by mjlarson** [comment]
Looks like we could pretty easily interface with gammapy for the attenuations:

https://docs.gammapy.org/0.18.2/modeling/gallery/spectral/plot_absorbed.html#absorption-spectral-model 

I don't know of any programs that convert numu to gamma-ray fluxes, though. If anyone has any suggestions, I'm sure we could figure out a way to make it all work.

**Comment by itaboada** [comment]
It turns out that Legend.py simulates gamma rays, not neutrinos. To use Legend.py to simulate neutrinos, we will need the proposed utility to calculate fluxes based on p-p and p-gamma processes.
