### ISSUE TITLE
Add luminosity function for a parametrization of the observed blazar population. 

### ISSUE THREAD

**Issue by itaboada** [icecube/FIRESONG#73]
This is a paper for blazars:
https://iopscience.iop.org/article/10.1088/2041-8205/800/2/L27

Warning: The Ajello 2012 and 2014 on this topic had a wrong sign in the function. 
It's described in Formulas 1-10

**Comment by mlincett** [comment]
Is this a duplicate of #71 ?

**Comment by itaboada** [comment]
Duplicate issue
